#!/usr/bin/php
<?php
if (stripos(php_sapi_name(), 'cli') === false) {
    printf("This file must be executed from CLI\n");
    exit();
}

require_once 'config.php';

$addr_port = explode('/', $config->base_url)[2];
$cwd = dirname(__FILE__) . '/public';

$process = proc_open('php -S ' . $addr_port, [STDOUT], $pipes, $cwd, null, ['bypass_shell' => true]);

if (is_resource($process)) {
    proc_close($process);
}
